# Generated by Django 4.1.7 on 2023-02-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kafedra nomi')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': '1. Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fan nomi')),
                ('cafedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_plan.cafedra')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': '2. Fanlar',
            },
        ),
    ]
