# Generated by Django 4.1.7 on 2023-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fakultet nomi')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': '3. Fakultetlar',
            },
        ),
    ]
