# Generated by Django 4.1.7 on 2023-02-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Yo'nalish nomi")),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='study_plan.faculty')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "4. Yo'nalishlar",
            },
        ),
    ]
