# Generated by Django 4.1.7 on 2023-02-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0003_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='education_type',
            field=models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], default='kunduzgi', max_length=10, verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='study_plan.faculty', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='science',
            name='cafedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_plan.cafedra', verbose_name='Kafedra'),
        ),
    ]
