# Generated by Django 4.1.7 on 2023-02-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0005_delete_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Yo'nalish nomi")),
                ('education_type', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], default='kunduzgi', max_length=10, verbose_name="Ta'lim turi")),
                ('study_time', models.IntegerField(default=4, verbose_name="O'qish muddati")),
                ('direction_code', models.IntegerField(verbose_name="Yo'nalish kodi")),
                ('admission_year', models.IntegerField(verbose_name='Qabul qilingan yil')),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='study_plan.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "4. Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_code', models.CharField(max_length=20, verbose_name='Fan kodi')),
                ('exam_type', models.CharField(choices=[('imtihon', 'Imtihon'), ('sinov', 'Sinov')], max_length=10, verbose_name='Yakuniy nazorat turi')),
                ('lesson_time', models.IntegerField(verbose_name='Umumiy dars soati')),
                ('lecture_time', models.IntegerField(default=0, verbose_name="Ma'ruza vaqti")),
                ('practice_time', models.IntegerField(default=0, verbose_name='Amaliyot vaqti')),
                ('seminar_time', models.IntegerField(default=0, verbose_name='Seminar vaqti')),
                ('laboratory_time', models.IntegerField(default=0, verbose_name='Labaratoriya vaqti')),
                ('independent_education_time', models.IntegerField(default=0, verbose_name="Mustaqil ta'lim")),
                ('professional_practice_time', models.IntegerField(default=0, verbose_name='Malakaviy amaliyot')),
                ('course_work_time', models.IntegerField(default=0, verbose_name='Kurs ishi')),
                ('study_semestr', models.IntegerField(verbose_name="O'quv semestr raqami")),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.direction', verbose_name="Yo'nalish")),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.science', verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan rejasi',
                'verbose_name_plural': '5. Rejalar',
            },
        ),
    ]
